//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_ALUMOS
    {
        public int AL_ID { get; set; }
        public string AL_CARNET { get; set; }
        public string AL_PNOMBRE { get; set; }
        public string AL_SNOMBRE { get; set; }
        public string AL_TNOMBRE { get; set; }
        public string AL_PAPELLIDO { get; set; }
        public string AL_SAPELLIDO { get; set; }
        public Nullable<System.DateTime> AL_FECHA_NAC { get; set; }
        public Nullable<System.DateTime> AL_FECHA_REG { get; set; }
        public string AL_ESTADO { get; set; }
        public Nullable<int> AL_SUCURSAL { get; set; }
        public string AL_MAIL { get; set; }
        public byte[] AL_FOTO { get; set; }
        public Nullable<int> AL_DIRECCION { get; set; }
    }
}
