#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSCollegeDB")]
	public partial class AlumnosDataContext : System.Data.Linq.DataContext
	{
		
		public static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    public void InsertAL_ALUMO(AL_ALUMO instance);
    public void UpdateAL_ALUMO(AL_ALUMO instance);
    public void InsertAL_ENCARGADO(AL_ENCARGADO instance);
    public void UpdateAL_ENCARGADO(AL_ENCARGADO instance);
    partial void DeleteAL_ENCARGADO(AL_ENCARGADO instance);
    #endregion
		
		public AlumnosDataContext() : 
				base(global::MSCAccesoDatos.Properties.Settings.Default.MSCollegeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AL_ALUMO> AL_ALUMOs
		{
			get
			{
				return this.GetTable<AL_ALUMO>();
			}
		}
		
		public System.Data.Linq.Table<AL_DIRECCIONE> AL_DIRECCIONEs
		{
			get
			{
				return this.GetTable<AL_DIRECCIONE>();
			}
		}
		
		public System.Data.Linq.Table<AL_ENCARGADO> AL_ENCARGADOs
		{
			get
			{
				return this.GetTable<AL_ENCARGADO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AL_ALUMOS")]
	public partial class AL_ALUMO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AL_ID;
		
		private string _AL_CARNET;
		
		private string _AL_PNOMBRE;
		
		private string _AL_SNOMBRE;
		
		private string _AL_TNOMBRE;
		
		private string _AL_PAPELLIDO;
		
		private string _AL_SAPELLIDO;
		
		private System.Nullable<System.DateTime> _AL_FECHA_NAC;
		
		private System.Nullable<System.DateTime> _AL_FECHA_REG;
		
		private System.Nullable<char> _AL_ESTADO;
		
		private System.Nullable<int> _AL_SUCURSAL;
		
		private string _AL_MAIL;
		
		private System.Data.Linq.Binary _AL_FOTO;
		
		private System.Nullable<int> _AL_DIRECCION;
		
		private EntitySet<AL_ENCARGADO> _AL_ENCARGADOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAL_IDChanging(int value);
    partial void OnAL_IDChanged();
    partial void OnAL_CARNETChanging(string value);
    partial void OnAL_CARNETChanged();
    partial void OnAL_PNOMBREChanging(string value);
    partial void OnAL_PNOMBREChanged();
    partial void OnAL_SNOMBREChanging(string value);
    partial void OnAL_SNOMBREChanged();
    partial void OnAL_TNOMBREChanging(string value);
    partial void OnAL_TNOMBREChanged();
    partial void OnAL_PAPELLIDOChanging(string value);
    partial void OnAL_PAPELLIDOChanged();
    partial void OnAL_SAPELLIDOChanging(string value);
    partial void OnAL_SAPELLIDOChanged();
    partial void OnAL_FECHA_NACChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_NACChanged();
    partial void OnAL_FECHA_REGChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_REGChanged();
    partial void OnAL_ESTADOChanging(System.Nullable<char> value);
    partial void OnAL_ESTADOChanged();
    partial void OnAL_SUCURSALChanging(System.Nullable<int> value);
    partial void OnAL_SUCURSALChanged();
    partial void OnAL_MAILChanging(string value);
    partial void OnAL_MAILChanged();
    partial void OnAL_FOTOChanging(System.Data.Linq.Binary value);
    partial void OnAL_FOTOChanged();
    partial void OnAL_DIRECCIONChanging(System.Nullable<int> value);
    partial void OnAL_DIRECCIONChanged();
    #endregion
		
		public AL_ALUMO()
		{
			this._AL_ENCARGADOs = new EntitySet<AL_ENCARGADO>(new Action<AL_ENCARGADO>(this.attach_AL_ENCARGADOs), new Action<AL_ENCARGADO>(this.detach_AL_ENCARGADOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AL_ID
		{
			get
			{
				return this._AL_ID;
			}
			set
			{
				if ((this._AL_ID != value))
				{
					this.OnAL_IDChanging(value);
					this.SendPropertyChanging();
					this._AL_ID = value;
					this.SendPropertyChanged("AL_ID");
					this.OnAL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_CARNET", DbType="NChar(10)")]
		public string AL_CARNET
		{
			get
			{
				return this._AL_CARNET;
			}
			set
			{
				if ((this._AL_CARNET != value))
				{
					this.OnAL_CARNETChanging(value);
					this.SendPropertyChanging();
					this._AL_CARNET = value;
					this.SendPropertyChanged("AL_CARNET");
					this.OnAL_CARNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PNOMBRE", DbType="NChar(10)")]
		public string AL_PNOMBRE
		{
			get
			{
				return this._AL_PNOMBRE;
			}
			set
			{
				if ((this._AL_PNOMBRE != value))
				{
					this.OnAL_PNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_PNOMBRE = value;
					this.SendPropertyChanged("AL_PNOMBRE");
					this.OnAL_PNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SNOMBRE", DbType="NChar(10)")]
		public string AL_SNOMBRE
		{
			get
			{
				return this._AL_SNOMBRE;
			}
			set
			{
				if ((this._AL_SNOMBRE != value))
				{
					this.OnAL_SNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_SNOMBRE = value;
					this.SendPropertyChanged("AL_SNOMBRE");
					this.OnAL_SNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_TNOMBRE", DbType="NChar(10)")]
		public string AL_TNOMBRE
		{
			get
			{
				return this._AL_TNOMBRE;
			}
			set
			{
				if ((this._AL_TNOMBRE != value))
				{
					this.OnAL_TNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_TNOMBRE = value;
					this.SendPropertyChanged("AL_TNOMBRE");
					this.OnAL_TNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PAPELLIDO", DbType="NChar(10)")]
		public string AL_PAPELLIDO
		{
			get
			{
				return this._AL_PAPELLIDO;
			}
			set
			{
				if ((this._AL_PAPELLIDO != value))
				{
					this.OnAL_PAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_PAPELLIDO = value;
					this.SendPropertyChanged("AL_PAPELLIDO");
					this.OnAL_PAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SAPELLIDO", DbType="NChar(10)")]
		public string AL_SAPELLIDO
		{
			get
			{
				return this._AL_SAPELLIDO;
			}
			set
			{
				if ((this._AL_SAPELLIDO != value))
				{
					this.OnAL_SAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_SAPELLIDO = value;
					this.SendPropertyChanged("AL_SAPELLIDO");
					this.OnAL_SAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_NAC", DbType="Date")]
		public System.Nullable<System.DateTime> AL_FECHA_NAC
		{
			get
			{
				return this._AL_FECHA_NAC;
			}
			set
			{
				if ((this._AL_FECHA_NAC != value))
				{
					this.OnAL_FECHA_NACChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_NAC = value;
					this.SendPropertyChanged("AL_FECHA_NAC");
					this.OnAL_FECHA_NACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_REG", DbType="DateTime")]
		public System.Nullable<System.DateTime> AL_FECHA_REG
		{
			get
			{
				return this._AL_FECHA_REG;
			}
			set
			{
				if ((this._AL_FECHA_REG != value))
				{
					this.OnAL_FECHA_REGChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_REG = value;
					this.SendPropertyChanged("AL_FECHA_REG");
					this.OnAL_FECHA_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> AL_ESTADO
		{
			get
			{
				return this._AL_ESTADO;
			}
			set
			{
				if ((this._AL_ESTADO != value))
				{
					this.OnAL_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._AL_ESTADO = value;
					this.SendPropertyChanged("AL_ESTADO");
					this.OnAL_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SUCURSAL", DbType="Int")]
		public System.Nullable<int> AL_SUCURSAL
		{
			get
			{
				return this._AL_SUCURSAL;
			}
			set
			{
				if ((this._AL_SUCURSAL != value))
				{
					this.OnAL_SUCURSALChanging(value);
					this.SendPropertyChanging();
					this._AL_SUCURSAL = value;
					this.SendPropertyChanged("AL_SUCURSAL");
					this.OnAL_SUCURSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_MAIL", DbType="VarChar(50)")]
		public string AL_MAIL
		{
			get
			{
				return this._AL_MAIL;
			}
			set
			{
				if ((this._AL_MAIL != value))
				{
					this.OnAL_MAILChanging(value);
					this.SendPropertyChanging();
					this._AL_MAIL = value;
					this.SendPropertyChanged("AL_MAIL");
					this.OnAL_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FOTO", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AL_FOTO
		{
			get
			{
				return this._AL_FOTO;
			}
			set
			{
				if ((this._AL_FOTO != value))
				{
					this.OnAL_FOTOChanging(value);
					this.SendPropertyChanging();
					this._AL_FOTO = value;
					this.SendPropertyChanged("AL_FOTO");
					this.OnAL_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_DIRECCION", DbType="Int")]
		public System.Nullable<int> AL_DIRECCION
		{
			get
			{
				return this._AL_DIRECCION;
			}
			set
			{
				if ((this._AL_DIRECCION != value))
				{
					this.OnAL_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._AL_DIRECCION = value;
					this.SendPropertyChanged("AL_DIRECCION");
					this.OnAL_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AL_ALUMO_AL_ENCARGADO", Storage="_AL_ENCARGADOs", ThisKey="AL_ID", OtherKey="EN_ALUMNO")]
		public EntitySet<AL_ENCARGADO> AL_ENCARGADOs
		{
			get
			{
				return this._AL_ENCARGADOs;
			}
			set
			{
				this._AL_ENCARGADOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AL_ENCARGADOs(AL_ENCARGADO entity)
		{
			this.SendPropertyChanging();
			entity.AL_ALUMO = this;
		}
		
		private void detach_AL_ENCARGADOs(AL_ENCARGADO entity)
		{
			this.SendPropertyChanging();
			entity.AL_ALUMO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AL_DIRECCIONES")]
	public partial class AL_DIRECCIONE
	{
		
		private int _DI_ID;
		
		private int _DI_ALUMNO;
		
		private string _DI_DIRECCION;
		
		private int _DI_PAIS;
		
		private int _DI_DEPARTAMENTO;
		
		private int _DI_MUNICIPIO;
		
		private char _DI_ESTADO;
		
		public AL_DIRECCIONE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_ID", DbType="Int NOT NULL")]
		public int DI_ID
		{
			get
			{
				return this._DI_ID;
			}
			set
			{
				if ((this._DI_ID != value))
				{
					this._DI_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_ALUMNO", DbType="Int NOT NULL")]
		public int DI_ALUMNO
		{
			get
			{
				return this._DI_ALUMNO;
			}
			set
			{
				if ((this._DI_ALUMNO != value))
				{
					this._DI_ALUMNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_DIRECCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string DI_DIRECCION
		{
			get
			{
				return this._DI_DIRECCION;
			}
			set
			{
				if ((this._DI_DIRECCION != value))
				{
					this._DI_DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_PAIS", DbType="Int NOT NULL")]
		public int DI_PAIS
		{
			get
			{
				return this._DI_PAIS;
			}
			set
			{
				if ((this._DI_PAIS != value))
				{
					this._DI_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DI_DEPARTAMENTO
		{
			get
			{
				return this._DI_DEPARTAMENTO;
			}
			set
			{
				if ((this._DI_DEPARTAMENTO != value))
				{
					this._DI_DEPARTAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_MUNICIPIO", DbType="Int NOT NULL")]
		public int DI_MUNICIPIO
		{
			get
			{
				return this._DI_MUNICIPIO;
			}
			set
			{
				if ((this._DI_MUNICIPIO != value))
				{
					this._DI_MUNICIPIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI_ESTADO", DbType="Char(1) NOT NULL")]
		public char DI_ESTADO
		{
			get
			{
				return this._DI_ESTADO;
			}
			set
			{
				if ((this._DI_ESTADO != value))
				{
					this._DI_ESTADO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AL_ENCARGADO")]
	public partial class AL_ENCARGADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EN_ID;
		
		private int _EN_ALUMNO;
		
		private string _EN_NOMBRE;
		
		private string _EN_DIRECCION;
		
		private string _EN_CELULAR;
		
		private string _EN_TELEFONO_CASA;
		
		private string _EN_TELEFONO_TRABAJO;
		
		private string _EN_PARENTESCO;
		
		private System.Nullable<char> _EN_PRICIPAL;
		
		private System.Nullable<char> _EN_ESTADO;
		
		private EntityRef<AL_ALUMO> _AL_ALUMO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEN_IDChanging(int value);
    partial void OnEN_IDChanged();
    partial void OnEN_ALUMNOChanging(int value);
    partial void OnEN_ALUMNOChanged();
    partial void OnEN_NOMBREChanging(string value);
    partial void OnEN_NOMBREChanged();
    partial void OnEN_DIRECCIONChanging(string value);
    partial void OnEN_DIRECCIONChanged();
    partial void OnEN_CELULARChanging(string value);
    partial void OnEN_CELULARChanged();
    partial void OnEN_TELEFONO_CASAChanging(string value);
    partial void OnEN_TELEFONO_CASAChanged();
    partial void OnEN_TELEFONO_TRABAJOChanging(string value);
    partial void OnEN_TELEFONO_TRABAJOChanged();
    partial void OnEN_PARENTESCOChanging(string value);
    partial void OnEN_PARENTESCOChanged();
    partial void OnEN_PRICIPALChanging(System.Nullable<char> value);
    partial void OnEN_PRICIPALChanged();
    partial void OnEN_ESTADOChanging(System.Nullable<char> value);
    partial void OnEN_ESTADOChanged();
    #endregion
		
		public AL_ENCARGADO()
		{
			this._AL_ALUMO = default(EntityRef<AL_ALUMO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EN_ID
		{
			get
			{
				return this._EN_ID;
			}
			set
			{
				if ((this._EN_ID != value))
				{
					this.OnEN_IDChanging(value);
					this.SendPropertyChanging();
					this._EN_ID = value;
					this.SendPropertyChanged("EN_ID");
					this.OnEN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_ALUMNO", DbType="Int NOT NULL")]
		public int EN_ALUMNO
		{
			get
			{
				return this._EN_ALUMNO;
			}
			set
			{
				if ((this._EN_ALUMNO != value))
				{
					if (this._AL_ALUMO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEN_ALUMNOChanging(value);
					this.SendPropertyChanging();
					this._EN_ALUMNO = value;
					this.SendPropertyChanged("EN_ALUMNO");
					this.OnEN_ALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EN_NOMBRE
		{
			get
			{
				return this._EN_NOMBRE;
			}
			set
			{
				if ((this._EN_NOMBRE != value))
				{
					this.OnEN_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._EN_NOMBRE = value;
					this.SendPropertyChanged("EN_NOMBRE");
					this.OnEN_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_DIRECCION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string EN_DIRECCION
		{
			get
			{
				return this._EN_DIRECCION;
			}
			set
			{
				if ((this._EN_DIRECCION != value))
				{
					this.OnEN_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._EN_DIRECCION = value;
					this.SendPropertyChanged("EN_DIRECCION");
					this.OnEN_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_CELULAR", DbType="VarChar(15)")]
		public string EN_CELULAR
		{
			get
			{
				return this._EN_CELULAR;
			}
			set
			{
				if ((this._EN_CELULAR != value))
				{
					this.OnEN_CELULARChanging(value);
					this.SendPropertyChanging();
					this._EN_CELULAR = value;
					this.SendPropertyChanged("EN_CELULAR");
					this.OnEN_CELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_TELEFONO_CASA", DbType="VarChar(15)")]
		public string EN_TELEFONO_CASA
		{
			get
			{
				return this._EN_TELEFONO_CASA;
			}
			set
			{
				if ((this._EN_TELEFONO_CASA != value))
				{
					this.OnEN_TELEFONO_CASAChanging(value);
					this.SendPropertyChanging();
					this._EN_TELEFONO_CASA = value;
					this.SendPropertyChanged("EN_TELEFONO_CASA");
					this.OnEN_TELEFONO_CASAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_TELEFONO_TRABAJO", DbType="VarChar(15)")]
		public string EN_TELEFONO_TRABAJO
		{
			get
			{
				return this._EN_TELEFONO_TRABAJO;
			}
			set
			{
				if ((this._EN_TELEFONO_TRABAJO != value))
				{
					this.OnEN_TELEFONO_TRABAJOChanging(value);
					this.SendPropertyChanging();
					this._EN_TELEFONO_TRABAJO = value;
					this.SendPropertyChanged("EN_TELEFONO_TRABAJO");
					this.OnEN_TELEFONO_TRABAJOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_PARENTESCO", DbType="VarChar(50)")]
		public string EN_PARENTESCO
		{
			get
			{
				return this._EN_PARENTESCO;
			}
			set
			{
				if ((this._EN_PARENTESCO != value))
				{
					this.OnEN_PARENTESCOChanging(value);
					this.SendPropertyChanging();
					this._EN_PARENTESCO = value;
					this.SendPropertyChanged("EN_PARENTESCO");
					this.OnEN_PARENTESCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_PRICIPAL", DbType="Char(1)")]
		public System.Nullable<char> EN_PRICIPAL
		{
			get
			{
				return this._EN_PRICIPAL;
			}
			set
			{
				if ((this._EN_PRICIPAL != value))
				{
					this.OnEN_PRICIPALChanging(value);
					this.SendPropertyChanging();
					this._EN_PRICIPAL = value;
					this.SendPropertyChanged("EN_PRICIPAL");
					this.OnEN_PRICIPALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EN_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> EN_ESTADO
		{
			get
			{
				return this._EN_ESTADO;
			}
			set
			{
				if ((this._EN_ESTADO != value))
				{
					this.OnEN_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._EN_ESTADO = value;
					this.SendPropertyChanged("EN_ESTADO");
					this.OnEN_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AL_ALUMO_AL_ENCARGADO", Storage="_AL_ALUMO", ThisKey="EN_ALUMNO", OtherKey="AL_ID", IsForeignKey=true)]
		public AL_ALUMO AL_ALUMO
		{
			get
			{
				return this._AL_ALUMO.Entity;
			}
			set
			{
				AL_ALUMO previousValue = this._AL_ALUMO.Entity;
				if (((previousValue != value) 
							|| (this._AL_ALUMO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AL_ALUMO.Entity = null;
						previousValue.AL_ENCARGADOs.Remove(this);
					}
					this._AL_ALUMO.Entity = value;
					if ((value != null))
					{
						value.AL_ENCARGADOs.Add(this);
						this._EN_ALUMNO = value.AL_ID;
					}
					else
					{
						this._EN_ALUMNO = default(int);
					}
					this.SendPropertyChanged("AL_ALUMO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
