//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSCollegeDBEntities : DbContext
    {
        public MSCollegeDBEntities()
            : base("name=MSCollegeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AL_ALUMOS> AL_ALUMOS { get; set; }
        public DbSet<CF_MAESTROS> CF_MAESTROS { get; set; }
    }
}
