#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSCollegeDB")]
	public partial class AlumnosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAL_ALUMO(AL_ALUMO instance);
    partial void UpdateAL_ALUMO(AL_ALUMO instance);
    partial void DeleteAL_ALUMO(AL_ALUMO instance);
    #endregion
		
		public AlumnosDataContext() : 
				base(global::MSCAccesoDatos.Properties.Settings.Default.MSCollegeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AL_ALUMO> AL_ALUMOs
		{
			get
			{
				return this.GetTable<AL_ALUMO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Agrega_Alumno")]
		public int sp_Agrega_Alumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_ID", DbType="Int")] System.Nullable<int> aL_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_CARNET", DbType="NChar(10)")] string aL_CARNET, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_PNOMBRE", DbType="NChar(10)")] string aL_PNOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_SNOMBRE", DbType="NChar(10)")] string aL_SNOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_TNOMBRE", DbType="NChar(10)")] string aL_TNOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_PAPELLIDO", DbType="NChar(10)")] string aL_PAPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_SAPELLIDO", DbType="NChar(10)")] string aL_SAPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_FECHA_NAC", DbType="Date")] System.Nullable<System.DateTime> aL_FECHA_NAC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_FECHA_REG", DbType="DateTime")] System.Nullable<System.DateTime> aL_FECHA_REG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_ESTADO", DbType="Char(1)")] System.Nullable<char> aL_ESTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_SUCURSAL", DbType="Int")] System.Nullable<int> aL_SUCURSAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_MAIL", DbType="VarChar(50)")] string aL_MAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_FOTO", DbType="Image")] System.Data.Linq.Binary aL_FOTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_DIRECCION", DbType="Int")] System.Nullable<int> aL_DIRECCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aL_ID, aL_CARNET, aL_PNOMBRE, aL_SNOMBRE, aL_TNOMBRE, aL_PAPELLIDO, aL_SAPELLIDO, aL_FECHA_NAC, aL_FECHA_REG, aL_ESTADO, aL_SUCURSAL, aL_MAIL, aL_FOTO, aL_DIRECCION);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AL_ALUMOS")]
	public sealed partial class AL_ALUMO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AL_ID;
		
		private string _AL_CARNET;
		
		private string _AL_PNOMBRE;
		
		private string _AL_SNOMBRE;
		
		private string _AL_TNOMBRE;
		
		private string _AL_PAPELLIDO;
		
		private string _AL_SAPELLIDO;
		
		private System.Nullable<System.DateTime> _AL_FECHA_NAC;
		
		private System.Nullable<System.DateTime> _AL_FECHA_REG;
		
		private System.Nullable<char> _AL_ESTADO;
		
		private System.Nullable<int> _AL_SUCURSAL;
		
		private string _AL_MAIL;
		
		private System.Data.Linq.Binary _AL_FOTO;
		
		private System.Nullable<int> _AL_DIRECCION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAL_IDChanging(int value);
    partial void OnAL_IDChanged();
    partial void OnAL_CARNETChanging(string value);
    partial void OnAL_CARNETChanged();
    partial void OnAL_PNOMBREChanging(string value);
    partial void OnAL_PNOMBREChanged();
    partial void OnAL_SNOMBREChanging(string value);
    partial void OnAL_SNOMBREChanged();
    partial void OnAL_TNOMBREChanging(string value);
    partial void OnAL_TNOMBREChanged();
    partial void OnAL_PAPELLIDOChanging(string value);
    partial void OnAL_PAPELLIDOChanged();
    partial void OnAL_SAPELLIDOChanging(string value);
    partial void OnAL_SAPELLIDOChanged();
    partial void OnAL_FECHA_NACChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_NACChanged();
    partial void OnAL_FECHA_REGChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_REGChanged();
    partial void OnAL_ESTADOChanging(System.Nullable<char> value);
    partial void OnAL_ESTADOChanged();
    partial void OnAL_SUCURSALChanging(System.Nullable<int> value);
    partial void OnAL_SUCURSALChanged();
    partial void OnAL_MAILChanging(string value);
    partial void OnAL_MAILChanged();
    partial void OnAL_FOTOChanging(System.Data.Linq.Binary value);
    partial void OnAL_FOTOChanged();
    partial void OnAL_DIRECCIONChanging(System.Nullable<int> value);
    partial void OnAL_DIRECCIONChanged();
    #endregion
		
		public AL_ALUMO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AL_ID
		{
			get
			{
				return this._AL_ID;
			}
			set
			{
				if ((this._AL_ID != value))
				{
					this.OnAL_IDChanging(value);
					this.SendPropertyChanging();
					this._AL_ID = value;
					this.SendPropertyChanged("AL_ID");
					this.OnAL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_CARNET", DbType="NChar(10)")]
		public string AL_CARNET
		{
			get
			{
				return this._AL_CARNET;
			}
			set
			{
				if ((this._AL_CARNET != value))
				{
					this.OnAL_CARNETChanging(value);
					this.SendPropertyChanging();
					this._AL_CARNET = value;
					this.SendPropertyChanged("AL_CARNET");
					this.OnAL_CARNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PNOMBRE", DbType="NChar(10)")]
		public string AL_PNOMBRE
		{
			get
			{
				return this._AL_PNOMBRE;
			}
			set
			{
				if ((this._AL_PNOMBRE != value))
				{
					this.OnAL_PNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_PNOMBRE = value;
					this.SendPropertyChanged("AL_PNOMBRE");
					this.OnAL_PNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SNOMBRE", DbType="NChar(10)")]
		public string AL_SNOMBRE
		{
			get
			{
				return this._AL_SNOMBRE;
			}
			set
			{
				if ((this._AL_SNOMBRE != value))
				{
					this.OnAL_SNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_SNOMBRE = value;
					this.SendPropertyChanged("AL_SNOMBRE");
					this.OnAL_SNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_TNOMBRE", DbType="NChar(10)")]
		public string AL_TNOMBRE
		{
			get
			{
				return this._AL_TNOMBRE;
			}
			set
			{
				if ((this._AL_TNOMBRE != value))
				{
					this.OnAL_TNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_TNOMBRE = value;
					this.SendPropertyChanged("AL_TNOMBRE");
					this.OnAL_TNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PAPELLIDO", DbType="NChar(10)")]
		public string AL_PAPELLIDO
		{
			get
			{
				return this._AL_PAPELLIDO;
			}
			set
			{
				if ((this._AL_PAPELLIDO != value))
				{
					this.OnAL_PAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_PAPELLIDO = value;
					this.SendPropertyChanged("AL_PAPELLIDO");
					this.OnAL_PAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SAPELLIDO", DbType="NChar(10)")]
		public string AL_SAPELLIDO
		{
			get
			{
				return this._AL_SAPELLIDO;
			}
			set
			{
				if ((this._AL_SAPELLIDO != value))
				{
					this.OnAL_SAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_SAPELLIDO = value;
					this.SendPropertyChanged("AL_SAPELLIDO");
					this.OnAL_SAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_NAC", DbType="Date")]
		public System.Nullable<System.DateTime> AL_FECHA_NAC
		{
			get
			{
				return this._AL_FECHA_NAC;
			}
			set
			{
				if ((this._AL_FECHA_NAC != value))
				{
					this.OnAL_FECHA_NACChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_NAC = value;
					this.SendPropertyChanged("AL_FECHA_NAC");
					this.OnAL_FECHA_NACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_REG", DbType="DateTime")]
		public System.Nullable<System.DateTime> AL_FECHA_REG
		{
			get
			{
				return this._AL_FECHA_REG;
			}
			set
			{
				if ((this._AL_FECHA_REG != value))
				{
					this.OnAL_FECHA_REGChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_REG = value;
					this.SendPropertyChanged("AL_FECHA_REG");
					this.OnAL_FECHA_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> AL_ESTADO
		{
			get
			{
				return this._AL_ESTADO;
			}
			set
			{
				if ((this._AL_ESTADO != value))
				{
					this.OnAL_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._AL_ESTADO = value;
					this.SendPropertyChanged("AL_ESTADO");
					this.OnAL_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SUCURSAL", DbType="Int")]
		public System.Nullable<int> AL_SUCURSAL
		{
			get
			{
				return this._AL_SUCURSAL;
			}
			set
			{
				if ((this._AL_SUCURSAL != value))
				{
					this.OnAL_SUCURSALChanging(value);
					this.SendPropertyChanging();
					this._AL_SUCURSAL = value;
					this.SendPropertyChanged("AL_SUCURSAL");
					this.OnAL_SUCURSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_MAIL", DbType="VarChar(50)")]
		public string AL_MAIL
		{
			get
			{
				return this._AL_MAIL;
			}
			set
			{
				if ((this._AL_MAIL != value))
				{
					this.OnAL_MAILChanging(value);
					this.SendPropertyChanging();
					this._AL_MAIL = value;
					this.SendPropertyChanged("AL_MAIL");
					this.OnAL_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FOTO", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AL_FOTO
		{
			get
			{
				return this._AL_FOTO;
			}
			set
			{
				if ((this._AL_FOTO != value))
				{
					this.OnAL_FOTOChanging(value);
					this.SendPropertyChanging();
					this._AL_FOTO = value;
					this.SendPropertyChanged("AL_FOTO");
					this.OnAL_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_DIRECCION", DbType="Int")]
		public System.Nullable<int> AL_DIRECCION
		{
			get
			{
				return this._AL_DIRECCION;
			}
			set
			{
				if ((this._AL_DIRECCION != value))
				{
					this.OnAL_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._AL_DIRECCION = value;
					this.SendPropertyChanged("AL_DIRECCION");
					this.OnAL_DIRECCIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		private void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		private void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
