<?xml version="1.0" encoding="utf-8"?><Database Name="MSCollegeDB" Class="AlumnosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=186.151.198.5;Initial Catalog=MSCollegeDB;Persist Security Info=True;User ID=sa" SettingsObjectName="MSCAccesoDatos.Properties.Settings" SettingsPropertyName="MSCollegeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AL_ALUMOS" Member="AL_ALUMOs">
    <Type Name="AL_ALUMO">
      <Column Name="AL_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AL_CARNET" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_PNOMBRE" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_SNOMBRE" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_TNOMBRE" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_PAPELLIDO" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_SAPELLIDO" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AL_FECHA_NAC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AL_FECHA_REG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AL_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AL_SUCURSAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AL_MAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AL_FOTO" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AL_DIRECCION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AL_ALUMO_AL_DIRECCIONE" Member="AL_DIRECCIONEs" ThisKey="AL_ID" OtherKey="DI_ALUMNO" Type="AL_DIRECCIONE" />
      <Association Name="AL_ALUMO_AL_ENCARGADO" Member="AL_ENCARGADOs" ThisKey="AL_ID" OtherKey="EN_ALUMNO" Type="AL_ENCARGADO" />
    </Type>
  </Table>
  <Table Name="dbo.AL_DIRECCIONES" Member="AL_DIRECCIONEs">
    <Type Name="AL_DIRECCIONE">
      <Column Name="DI_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DI_ALUMNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DI_DIRECCION" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DI_PAIS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DI_DEPARTAMENTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DI_MUNICIPIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DI_ESTADO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="AL_ALUMO_AL_DIRECCIONE" Member="AL_ALUMO" ThisKey="DI_ALUMNO" OtherKey="AL_ID" Type="AL_ALUMO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AL_ENCARGADO" Member="AL_ENCARGADOs">
    <Type Name="AL_ENCARGADO">
      <Column Name="EN_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EN_ALUMNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EN_NOMBRE" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EN_DIRECCION" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EN_CELULAR" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EN_TELEFONO_CASA" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EN_TELEFONO_TRABAJO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EN_PARENTESCO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EN_PRICIPAL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EN_ESTADO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="AL_ALUMO_AL_ENCARGADO" Member="AL_ALUMO" ThisKey="EN_ALUMNO" OtherKey="AL_ID" Type="AL_ALUMO" IsForeignKey="true" />
    </Type>
  </Table>
</Database>