#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSCollegeDB")]
	public partial class AlumnosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAL_ALUMO(AL_ALUMO instance);
    partial void UpdateAL_ALUMO(AL_ALUMO instance);
    partial void DeleteAL_ALUMO(AL_ALUMO instance);
    partial void InsertCF_MAESTRO(CF_MAESTRO instance);
    partial void UpdateCF_MAESTRO(CF_MAESTRO instance);
    partial void DeleteCF_MAESTRO(CF_MAESTRO instance);
    #endregion
		
		public AlumnosDataContext() : 
				base(global::MSCAccesoDatos.Properties.Settings.Default.MSCollegeDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumnosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AL_ALUMO> AL_ALUMOs
		{
			get
			{
				return this.GetTable<AL_ALUMO>();
			}
		}
		
		public System.Data.Linq.Table<CF_MAESTRO> CF_MAESTROs
		{
			get
			{
				return this.GetTable<CF_MAESTRO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AL_ALUMOS")]
	public partial class AL_ALUMO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AL_ID;
		
		private string _AL_CARNET;
		
		private string _AL_PNOMBRE;
		
		private string _AL_SNOMBRE;
		
		private string _AL_TNOMBRE;
		
		private string _AL_PAPELLIDO;
		
		private string _AL_SAPELLIDO;
		
		private System.Nullable<System.DateTime> _AL_FECHA_NAC;
		
		private System.Nullable<System.DateTime> _AL_FECHA_REG;
		
		private System.Nullable<char> _AL_ESTADO;
		
		private System.Nullable<int> _AL_SUCURSAL;
		
		private string _AL_MAIL;
		
		private System.Data.Linq.Binary _AL_FOTO;
		
		private System.Nullable<int> _AL_DIRECCION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAL_IDChanging(int value);
    partial void OnAL_IDChanged();
    partial void OnAL_CARNETChanging(string value);
    partial void OnAL_CARNETChanged();
    partial void OnAL_PNOMBREChanging(string value);
    partial void OnAL_PNOMBREChanged();
    partial void OnAL_SNOMBREChanging(string value);
    partial void OnAL_SNOMBREChanged();
    partial void OnAL_TNOMBREChanging(string value);
    partial void OnAL_TNOMBREChanged();
    partial void OnAL_PAPELLIDOChanging(string value);
    partial void OnAL_PAPELLIDOChanged();
    partial void OnAL_SAPELLIDOChanging(string value);
    partial void OnAL_SAPELLIDOChanged();
    partial void OnAL_FECHA_NACChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_NACChanged();
    partial void OnAL_FECHA_REGChanging(System.Nullable<System.DateTime> value);
    partial void OnAL_FECHA_REGChanged();
    partial void OnAL_ESTADOChanging(System.Nullable<char> value);
    partial void OnAL_ESTADOChanged();
    partial void OnAL_SUCURSALChanging(System.Nullable<int> value);
    partial void OnAL_SUCURSALChanged();
    partial void OnAL_MAILChanging(string value);
    partial void OnAL_MAILChanged();
    partial void OnAL_FOTOChanging(System.Data.Linq.Binary value);
    partial void OnAL_FOTOChanged();
    partial void OnAL_DIRECCIONChanging(System.Nullable<int> value);
    partial void OnAL_DIRECCIONChanged();
    #endregion
		
		public AL_ALUMO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AL_ID
		{
			get
			{
				return this._AL_ID;
			}
			set
			{
				if ((this._AL_ID != value))
				{
					this.OnAL_IDChanging(value);
					this.SendPropertyChanging();
					this._AL_ID = value;
					this.SendPropertyChanged("AL_ID");
					this.OnAL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_CARNET", DbType="NChar(10)")]
		public string AL_CARNET
		{
			get
			{
				return this._AL_CARNET;
			}
			set
			{
				if ((this._AL_CARNET != value))
				{
					this.OnAL_CARNETChanging(value);
					this.SendPropertyChanging();
					this._AL_CARNET = value;
					this.SendPropertyChanged("AL_CARNET");
					this.OnAL_CARNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PNOMBRE", DbType="NChar(10)")]
		public string AL_PNOMBRE
		{
			get
			{
				return this._AL_PNOMBRE;
			}
			set
			{
				if ((this._AL_PNOMBRE != value))
				{
					this.OnAL_PNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_PNOMBRE = value;
					this.SendPropertyChanged("AL_PNOMBRE");
					this.OnAL_PNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SNOMBRE", DbType="NChar(10)")]
		public string AL_SNOMBRE
		{
			get
			{
				return this._AL_SNOMBRE;
			}
			set
			{
				if ((this._AL_SNOMBRE != value))
				{
					this.OnAL_SNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_SNOMBRE = value;
					this.SendPropertyChanged("AL_SNOMBRE");
					this.OnAL_SNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_TNOMBRE", DbType="NChar(10)")]
		public string AL_TNOMBRE
		{
			get
			{
				return this._AL_TNOMBRE;
			}
			set
			{
				if ((this._AL_TNOMBRE != value))
				{
					this.OnAL_TNOMBREChanging(value);
					this.SendPropertyChanging();
					this._AL_TNOMBRE = value;
					this.SendPropertyChanged("AL_TNOMBRE");
					this.OnAL_TNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_PAPELLIDO", DbType="NChar(10)")]
		public string AL_PAPELLIDO
		{
			get
			{
				return this._AL_PAPELLIDO;
			}
			set
			{
				if ((this._AL_PAPELLIDO != value))
				{
					this.OnAL_PAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_PAPELLIDO = value;
					this.SendPropertyChanged("AL_PAPELLIDO");
					this.OnAL_PAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SAPELLIDO", DbType="NChar(10)")]
		public string AL_SAPELLIDO
		{
			get
			{
				return this._AL_SAPELLIDO;
			}
			set
			{
				if ((this._AL_SAPELLIDO != value))
				{
					this.OnAL_SAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._AL_SAPELLIDO = value;
					this.SendPropertyChanged("AL_SAPELLIDO");
					this.OnAL_SAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_NAC", DbType="Date")]
		public System.Nullable<System.DateTime> AL_FECHA_NAC
		{
			get
			{
				return this._AL_FECHA_NAC;
			}
			set
			{
				if ((this._AL_FECHA_NAC != value))
				{
					this.OnAL_FECHA_NACChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_NAC = value;
					this.SendPropertyChanged("AL_FECHA_NAC");
					this.OnAL_FECHA_NACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FECHA_REG", DbType="DateTime")]
		public System.Nullable<System.DateTime> AL_FECHA_REG
		{
			get
			{
				return this._AL_FECHA_REG;
			}
			set
			{
				if ((this._AL_FECHA_REG != value))
				{
					this.OnAL_FECHA_REGChanging(value);
					this.SendPropertyChanging();
					this._AL_FECHA_REG = value;
					this.SendPropertyChanged("AL_FECHA_REG");
					this.OnAL_FECHA_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> AL_ESTADO
		{
			get
			{
				return this._AL_ESTADO;
			}
			set
			{
				if ((this._AL_ESTADO != value))
				{
					this.OnAL_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._AL_ESTADO = value;
					this.SendPropertyChanged("AL_ESTADO");
					this.OnAL_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_SUCURSAL", DbType="Int")]
		public System.Nullable<int> AL_SUCURSAL
		{
			get
			{
				return this._AL_SUCURSAL;
			}
			set
			{
				if ((this._AL_SUCURSAL != value))
				{
					this.OnAL_SUCURSALChanging(value);
					this.SendPropertyChanging();
					this._AL_SUCURSAL = value;
					this.SendPropertyChanged("AL_SUCURSAL");
					this.OnAL_SUCURSALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_MAIL", DbType="VarChar(50)")]
		public string AL_MAIL
		{
			get
			{
				return this._AL_MAIL;
			}
			set
			{
				if ((this._AL_MAIL != value))
				{
					this.OnAL_MAILChanging(value);
					this.SendPropertyChanging();
					this._AL_MAIL = value;
					this.SendPropertyChanged("AL_MAIL");
					this.OnAL_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_FOTO", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AL_FOTO
		{
			get
			{
				return this._AL_FOTO;
			}
			set
			{
				if ((this._AL_FOTO != value))
				{
					this.OnAL_FOTOChanging(value);
					this.SendPropertyChanging();
					this._AL_FOTO = value;
					this.SendPropertyChanged("AL_FOTO");
					this.OnAL_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_DIRECCION", DbType="Int")]
		public System.Nullable<int> AL_DIRECCION
		{
			get
			{
				return this._AL_DIRECCION;
			}
			set
			{
				if ((this._AL_DIRECCION != value))
				{
					this.OnAL_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._AL_DIRECCION = value;
					this.SendPropertyChanged("AL_DIRECCION");
					this.OnAL_DIRECCIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CF_MAESTROS")]
	public partial class CF_MAESTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_ID;
		
		private string _MA_PNOMBRE;
		
		private string _MA_SNOMBRE;
		
		private string _MA_PAPELLIDO;
		
		private string _MA_SAPELLIDO;
		
		private string _MA_APCASADO;
		
		private string _MA_DIRECCION;
		
		private string _MA_TELEFONO;
		
		private string _MA_MAIL;
		
		private System.Nullable<char> _MA_ESTADO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_IDChanging(int value);
    partial void OnMA_IDChanged();
    partial void OnMA_PNOMBREChanging(string value);
    partial void OnMA_PNOMBREChanged();
    partial void OnMA_SNOMBREChanging(string value);
    partial void OnMA_SNOMBREChanged();
    partial void OnMA_PAPELLIDOChanging(string value);
    partial void OnMA_PAPELLIDOChanged();
    partial void OnMA_SAPELLIDOChanging(string value);
    partial void OnMA_SAPELLIDOChanged();
    partial void OnMA_APCASADOChanging(string value);
    partial void OnMA_APCASADOChanged();
    partial void OnMA_DIRECCIONChanging(string value);
    partial void OnMA_DIRECCIONChanged();
    partial void OnMA_TELEFONOChanging(string value);
    partial void OnMA_TELEFONOChanged();
    partial void OnMA_MAILChanging(string value);
    partial void OnMA_MAILChanged();
    partial void OnMA_ESTADOChanging(System.Nullable<char> value);
    partial void OnMA_ESTADOChanged();
    #endregion
		
		public CF_MAESTRO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_ID
		{
			get
			{
				return this._MA_ID;
			}
			set
			{
				if ((this._MA_ID != value))
				{
					this.OnMA_IDChanging(value);
					this.SendPropertyChanging();
					this._MA_ID = value;
					this.SendPropertyChanged("MA_ID");
					this.OnMA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PNOMBRE", DbType="VarChar(50)")]
		public string MA_PNOMBRE
		{
			get
			{
				return this._MA_PNOMBRE;
			}
			set
			{
				if ((this._MA_PNOMBRE != value))
				{
					this.OnMA_PNOMBREChanging(value);
					this.SendPropertyChanging();
					this._MA_PNOMBRE = value;
					this.SendPropertyChanged("MA_PNOMBRE");
					this.OnMA_PNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SNOMBRE", DbType="VarChar(50)")]
		public string MA_SNOMBRE
		{
			get
			{
				return this._MA_SNOMBRE;
			}
			set
			{
				if ((this._MA_SNOMBRE != value))
				{
					this.OnMA_SNOMBREChanging(value);
					this.SendPropertyChanging();
					this._MA_SNOMBRE = value;
					this.SendPropertyChanged("MA_SNOMBRE");
					this.OnMA_SNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PAPELLIDO", DbType="VarChar(50)")]
		public string MA_PAPELLIDO
		{
			get
			{
				return this._MA_PAPELLIDO;
			}
			set
			{
				if ((this._MA_PAPELLIDO != value))
				{
					this.OnMA_PAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._MA_PAPELLIDO = value;
					this.SendPropertyChanged("MA_PAPELLIDO");
					this.OnMA_PAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SAPELLIDO", DbType="VarChar(50)")]
		public string MA_SAPELLIDO
		{
			get
			{
				return this._MA_SAPELLIDO;
			}
			set
			{
				if ((this._MA_SAPELLIDO != value))
				{
					this.OnMA_SAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._MA_SAPELLIDO = value;
					this.SendPropertyChanged("MA_SAPELLIDO");
					this.OnMA_SAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_APCASADO", DbType="VarChar(50)")]
		public string MA_APCASADO
		{
			get
			{
				return this._MA_APCASADO;
			}
			set
			{
				if ((this._MA_APCASADO != value))
				{
					this.OnMA_APCASADOChanging(value);
					this.SendPropertyChanging();
					this._MA_APCASADO = value;
					this.SendPropertyChanged("MA_APCASADO");
					this.OnMA_APCASADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DIRECCION", DbType="VarChar(255)")]
		public string MA_DIRECCION
		{
			get
			{
				return this._MA_DIRECCION;
			}
			set
			{
				if ((this._MA_DIRECCION != value))
				{
					this.OnMA_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._MA_DIRECCION = value;
					this.SendPropertyChanged("MA_DIRECCION");
					this.OnMA_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TELEFONO", DbType="VarChar(20)")]
		public string MA_TELEFONO
		{
			get
			{
				return this._MA_TELEFONO;
			}
			set
			{
				if ((this._MA_TELEFONO != value))
				{
					this.OnMA_TELEFONOChanging(value);
					this.SendPropertyChanging();
					this._MA_TELEFONO = value;
					this.SendPropertyChanged("MA_TELEFONO");
					this.OnMA_TELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MAIL", DbType="VarChar(50)")]
		public string MA_MAIL
		{
			get
			{
				return this._MA_MAIL;
			}
			set
			{
				if ((this._MA_MAIL != value))
				{
					this.OnMA_MAILChanging(value);
					this.SendPropertyChanging();
					this._MA_MAIL = value;
					this.SendPropertyChanged("MA_MAIL");
					this.OnMA_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> MA_ESTADO
		{
			get
			{
				return this._MA_ESTADO;
			}
			set
			{
				if ((this._MA_ESTADO != value))
				{
					this.OnMA_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._MA_ESTADO = value;
					this.SendPropertyChanged("MA_ESTADO");
					this.OnMA_ESTADOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
