//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CF_MAESTROS
    {
        public int MA_ID { get; set; }
        public string MA_PNOMBRE { get; set; }
        public string MA_SNOMBRE { get; set; }
        public string MA_PAPELLIDO { get; set; }
        public string MA_SAPELLIDO { get; set; }
        public string MA_APCASADO { get; set; }
        public string MA_DIRECCION { get; set; }
        public string MA_TELEFONO { get; set; }
        public string MA_MAIL { get; set; }
        public string MA_ESTADO { get; set; }
    }
}
