<?xml version="1.0" encoding="utf-8"?><Database Name="COLEGIOS" Class="ConfiguracionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADM;Initial Catalog=COLEGIOS;User ID=sa" SettingsObjectName="MSCAccesoDatos.Properties.Settings" SettingsPropertyName="COLEGIOSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CF_COLEGIO" Member="CF_COLEGIOs">
    <Type Name="CF_COLEGIO">
      <Column Name="CL_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CL_NOMBRE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CL_DIRECCION" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CL_REPRESENTANTE_LEGAL" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CL_TELEFONO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CL_PAIS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CF_SUCURSALES" Member="CF_SUCURSALEs">
    <Type Name="CF_SUCURSALE">
      <Column Name="SU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SU_NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SU_DIRECCION" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CF_SUCURSAL" Member="CF_SUCURSALs">
    <Type Name="CF_SUCURSAL">
      <Column Name="SU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SU_NOMBRE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SU_DIRECCION" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SU_ENCARGADO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SU_TELEFONO" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SU_ESTADO" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>